# Generated by Django 5.0 on 2024-01-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=250)),
                ('occupation', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
